#!/usr/bin/env bash
#
# Setup script for claude-remote
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/bin"

echo "Claude Remote Setup"
echo "==================="
echo

# Create config.sh if it doesn't exist
if [[ ! -f "$SCRIPT_DIR/config.sh" ]]; then
    echo "Creating configuration..."
    echo

    # Prompt for values
    read -p "Remote SSH host (e.g., ubuntu@your-server.com): " REMOTE_HOST
    read -p "Remote mirror root [/home/ubuntu/claude-remote-mirror]: " REMOTE_MIRROR_ROOT
    REMOTE_MIRROR_ROOT="${REMOTE_MIRROR_ROOT:-/home/ubuntu/claude-remote-mirror}"

    read -p "PATH_IDENTITY mode — sync to identical absolute path on box? [y/N]: " pi_answer
    case "$pi_answer" in
        [Yy]*) PATH_IDENTITY="true" ;;
        *)     PATH_IDENTITY="false" ;;
    esac

    cat > "$SCRIPT_DIR/config.sh" << EOF
# Claude Remote Configuration
# Generated by setup.sh

REMOTE_HOST="$REMOTE_HOST"
REMOTE_MIRROR_ROOT="$REMOTE_MIRROR_ROOT"

# PATH_IDENTITY: when true, sync to the identical absolute path on the remote box.
# When false (default/legacy), paths are mirrored under REMOTE_MIRROR_ROOT.
PATH_IDENTITY="$PATH_IDENTITY"
EOF

    echo
    echo "✓ Configuration saved to config.sh"
else
    echo "✓ config.sh already exists"
    source "$SCRIPT_DIR/config.sh"
fi

echo

# Make scripts executable
chmod +x "$SCRIPT_DIR/scripts/"*.sh

# Create bin directory if needed
mkdir -p "$BIN_DIR"

# Create state directory (idempotent)
CR_STATE_DIR="${CLAUDE_REMOTE_STATE_DIR:-$HOME/.claude-remote}"
mkdir -p "$CR_STATE_DIR"
echo "✓ State dir: $CR_STATE_DIR"

# Create symlinks
echo "Creating symlinks in $BIN_DIR..."

COMMANDS=(claude-remote crfs sync-start sync-status sync-stop sync-reap remote-status paste-image-remote install-mutagen-agent)
for cmd in "${COMMANDS[@]}"; do
    if [[ -f "$SCRIPT_DIR/scripts/${cmd}.sh" ]]; then
        ln -sf "$SCRIPT_DIR/scripts/${cmd}.sh" "$BIN_DIR/$cmd"
        echo "  $cmd -> scripts/${cmd}.sh"
    fi
done

echo

# Check if ~/bin is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo "⚠ Warning: $BIN_DIR is not in your PATH"
    echo "  Add this to your ~/.zshrc or ~/.bashrc:"
    echo "  export PATH=\"\$HOME/bin:\$PATH\""
    echo
fi

# Check dependencies
echo "Checking dependencies..."

if ! command -v mutagen &> /dev/null; then
    echo "⚠ mutagen not found. Install it:"
    echo "    macOS:  brew install mutagen-io/mutagen/mutagen"
    echo "    Linux:  download the release tarball from"
    echo "            https://github.com/mutagen-io/mutagen/releases and place"
    echo "            'mutagen' + 'mutagen-agents.tar.gz' on your PATH (e.g. ~/.local/bin)"
else
    echo "✓ mutagen installed ($(mutagen version 2>/dev/null))"
fi

# sshfs is only needed for crfs (SSHFS direct mode); warn softly.
if ! command -v sshfs &> /dev/null; then
    echo "ℹ sshfs not found (only needed for 'crfs' SSHFS-direct mode)."
    echo "    Linux: sudo apt install sshfs   |   macOS: install macFUSE + sshfs"
fi

if ! command -v claude &> /dev/null; then
    echo "⚠ claude not found. Install Claude Code first."
else
    echo "✓ claude installed"
fi

echo

# Test SSH connection
echo "Testing SSH connection to $REMOTE_HOST..."
if ssh -o ConnectTimeout=5 -o BatchMode=yes "$REMOTE_HOST" "echo ok" &> /dev/null; then
    echo "✓ SSH connection works"

    # === PATH_IDENTITY box-side setup ===
    # When PATH_IDENTITY=true, the box must have /Users/<localuser> created and
    # owned by the ssh user so mutagen can sync to the identical absolute path.
    # We derive the local username from $HOME (e.g. /Users/alice -> alice).
    if [[ "${PATH_IDENTITY:-false}" == "true" ]]; then
        echo
        echo "PATH_IDENTITY=true: setting up identity path on box..."
        local_user="$(basename "$HOME")"
        # Extract just the username part from REMOTE_HOST (user@host -> user)
        remote_user="${REMOTE_HOST%%@*}"
        echo "  Creating /Users/$local_user on box owned by $remote_user..."
        if ssh -o ConnectTimeout=5 "$REMOTE_HOST" \
            "sudo mkdir -p /Users/$local_user && sudo chown $remote_user:$remote_user /Users /Users/$local_user" 2>/dev/null; then
            echo "  OK: /Users/$local_user exists and is owned by $remote_user"
        else
            echo "  Warning: could not create /Users/$local_user on box (sudo may not be available)."
            echo "  Run manually: sudo mkdir -p /Users/$local_user && sudo chown ubuntu:ubuntu /Users /Users/$local_user"
        fi
    fi
else
    echo "Warning: SSH connection failed. Make sure:"
    echo "  1. The host is reachable"
    echo "  2. SSH keys are set up (ssh-copy-id $REMOTE_HOST)"
fi

echo
echo "Setup complete!"
echo
echo "Usage:"
echo "  claude-remote          # Launch Claude with remote execution (syncs CWD)"
echo "  sync-start [path]      # Start Mutagen sync for a directory"
echo "  sync-status            # Show Mutagen sync status"
echo "  sync-stop              # Stop Mutagen sync"
echo "  remote-status          # Diagnostic status check"
