#!/usr/bin/env bash
#
# claude-server — LOCAL machine installer.
#
# Installs dependencies, generates an SSH key, writes config.sh + ~/.ssh/config
# (with a permanent shared SSH master), creates the command symlinks, then
# onboards the remote and verifies the connection.
#
# Run from inside the cloned repo:   bash install/local.sh
#

set -euo pipefail

REPO_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OS="$(uname -s)"

c_say(){ printf '\033[1;36m==>\033[0m %s\n' "$*"; }
c_warn(){ printf '\033[1;33m!\033[0m  %s\n' "$*"; }
c_ok(){ printf '\033[1;32m✓\033[0m  %s\n' "$*"; }

echo "======================================"
echo " claude-server — local setup"
echo "======================================"

# --- 1. Mutagen ---------------------------------------------------------------
if ! command -v mutagen >/dev/null 2>&1; then
    c_say "Installing Mutagen..."
    if [ "$OS" = "Darwin" ]; then
        brew install mutagen-io/mutagen/mutagen
    else
        mkdir -p "$HOME/.local/bin"
        TAG="$(curl -fsSL https://api.github.com/repos/mutagen-io/mutagen/releases/latest | grep -m1 '"tag_name"' | cut -d'"' -f4)"
        case "$(uname -m)" in x86_64|amd64) MA=amd64;; aarch64|arm64) MA=arm64;; *) MA=amd64;; esac
        curl -fsSL "https://github.com/mutagen-io/mutagen/releases/download/${TAG}/mutagen_linux_${MA}_${TAG}.tar.gz" | tar -xz -C /tmp
        install -m755 /tmp/mutagen "$HOME/.local/bin/mutagen"
        cp /tmp/mutagen-agents.tar.gz "$HOME/.local/bin/"   # MUST sit next to the binary
    fi
fi
c_ok "Mutagen $(mutagen version 2>/dev/null || echo '?')"

# --- 2. sshfs (optional, Mode B) ----------------------------------------------
if ! command -v sshfs >/dev/null 2>&1; then
    c_warn "sshfs not found (needed only for 'crfs' SSHFS-direct mode)."
    [ "$OS" = "Linux" ]  && c_warn "  install: sudo apt install sshfs"
    [ "$OS" = "Darwin" ] && c_warn "  install: macFUSE + sshfs (https://osxfuse.github.io)"
else
    c_ok "sshfs present"
fi

# --- 2b. optional Tailscale (for NAT'd / IPv6-only remotes) -------------------
echo
read -rp "Set up Tailscale on THIS machine now? (recommended if the remote is behind NAT) [y/N]: " TS
if [[ "${TS:-}" =~ ^[Yy] ]]; then
    bash "$REPO_DIR/install/tailscale.sh" "$(hostname)" || c_warn "Tailscale step skipped"
    echo "  → make sure the REMOTE is also on the tailnet, then use its 100.x IP below."
fi

# --- 3. gather connection details ---------------------------------------------
echo
read -rp "Remote SSH host (user@host or user@tailscale-ip): " REMOTE_HOST
[ -n "$REMOTE_HOST" ] || { echo "host required"; exit 1; }
USER_ONLY="${REMOTE_HOST%@*}"; HOST_ONLY="${REMOTE_HOST#*@}"
read -rp "SSH port [22]: " SSH_PORT; SSH_PORT="${SSH_PORT:-22}"
read -rp "Remote mirror root [/home/${USER_ONLY}/claude-server-mirror]: " REMOTE_MIRROR_ROOT
REMOTE_MIRROR_ROOT="${REMOTE_MIRROR_ROOT:-/home/${USER_ONLY}/claude-server-mirror}"

# --- 4. SSH key ---------------------------------------------------------------
KEY="$HOME/.ssh/claude_server_ed25519"
mkdir -p "$HOME/.ssh"; chmod 700 "$HOME/.ssh"
if [ ! -f "$KEY" ]; then
    c_say "Generating SSH key ($KEY)..."
    ssh-keygen -t ed25519 -N '' -C "claude-server@$(hostname)" -f "$KEY" >/dev/null
fi
c_ok "SSH key ready"

# --- 5. ~/.ssh/config (permanent shared master) -------------------------------
touch "$HOME/.ssh/config"; chmod 600 "$HOME/.ssh/config"
if ! grep -qE "^Host ${HOST_ONLY}$" "$HOME/.ssh/config"; then
    c_say "Writing ~/.ssh/config entry for ${HOST_ONLY}..."
    cat >> "$HOME/.ssh/config" <<EOF

# --- claude-server ---
Host ${HOST_ONLY}
    HostName ${HOST_ONLY}
    User ${USER_ONLY}
    Port ${SSH_PORT}
    IdentityFile ${KEY}
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
    ServerAliveInterval 30
    ServerAliveCountMax 3
    TCPKeepAlive yes
    ControlMaster auto
    ControlPath /tmp/ssh-claude-%r@%h:%p
    ControlPersist yes
EOF
fi
c_ok "~/.ssh/config ready"

# --- 6. config.sh -------------------------------------------------------------
cat > "$REPO_DIR/config.sh" <<EOF
# Generated by install/local.sh
REMOTE_HOST="${REMOTE_HOST}"
REMOTE_MIRROR_ROOT="${REMOTE_MIRROR_ROOT}"
PATH_IDENTITY="false"
EOF
c_ok "config.sh written"

# --- 7. command symlinks ------------------------------------------------------
c_say "Creating command symlinks..."
bash "$REPO_DIR/setup.sh" </dev/null || true

# --- 8. ~/bin on PATH ---------------------------------------------------------
RC="$HOME/.bashrc"; [ "$OS" = "Darwin" ] && RC="$HOME/.zshrc"
case ":$PATH:" in
    *":$HOME/bin:"*) ;;
    *) echo 'export PATH="$HOME/bin:$PATH"' >> "$RC"; export PATH="$HOME/bin:$PATH"
       c_ok "Added ~/bin to PATH in $RC" ;;
esac

# --- 9. onboard the remote ----------------------------------------------------
PUB="$(cat "$KEY.pub")"
echo
echo "--------------------------------------------------------------------"
echo " Now run the REMOTE setup on ${REMOTE_HOST}. Either:"
echo
echo "   curl -fsSL https://raw.githubusercontent.com/szl666/claude-server/main/install/remote.sh | bash -s -- '${PUB}'"
echo
echo "   ...or copy install/remote.sh to the box and run:"
echo "   bash remote.sh '${PUB}'"
echo "--------------------------------------------------------------------"
echo
read -rp "Press Enter AFTER the remote setup has finished... " _ || true

# --- 10. verify + pre-install Mutagen agent -----------------------------------
c_say "Testing SSH to ${REMOTE_HOST}..."
if ssh -o BatchMode=yes -o ConnectTimeout=10 "$REMOTE_HOST" 'echo ok' >/dev/null 2>&1; then
    c_ok "SSH works"
    c_say "Pre-installing Mutagen agent (needed for zsh/fish remote shells)..."
    bash "$REPO_DIR/scripts/install-mutagen-agent.sh" || c_warn "agent pre-install skipped (will retry on first sync)"
    echo
    c_ok "Done!"
    echo "    Mode A (local project → remote CPU):   cd <project> && claude-remote"
    echo "    Mode B (remote project, no local disk): crfs /remote/abs/path"
    echo "    Enable remote routing:  printf 'on\\n' > ~/.claude-remote/mode"
else
    c_warn "SSH test failed. Check: remote setup ran, host/port correct, key added."
    c_warn "Re-run this script after fixing, or test: ssh ${REMOTE_HOST} 'echo ok'"
fi
